name: teste_flutter_target
description: Target admission test.
publish_to: 'none'

version: 0.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  dio: ^5.3.4
  http_mock_adapter: ^0.6.1
  mobx: ^2.2.1
  get_it: ^7.6.4
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.6
  mockito: ^5.4.3

flutter:
  uses-material-design: true
