name: teste_flutter_target
description: Target admission test.
publish_to: 'none'

version: 0.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^5.3.4
  http_mock_adapter: ^0.4.4
  mobx: ^2.2.1
  get_it: ^7.6.0
  shared_preferences: ^0.5.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  mockito: ^5.4.0

flutter:
  uses-material-design: true
